/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "oauth.h"

char **client_ids;
char **client_access_tokens;
char **client_refresh_tokens;
int *client_refresh_states;
int *client_ttls;
int client_nr_users = 0;
int ttl;

void
checkprog_1(char *host)
{
	CLIENT *clnt;
	struct auth_response  *result_1;
	char * request_auth_1_arg;
	struct approve_request  *result_2;
	struct approve_request  approve_request_token_1_arg;
	struct access_response  *result_3;
	struct access_request  request_access_1_arg;
	int  *result_4;
	struct action_request  validate_delegated_action_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, OAUTH_PROG, OAUTH_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = request_auth_1(&request_auth_1_arg, clnt);
	if (result_1 == (struct auth_response *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = approve_request_token_1(&approve_request_token_1_arg, clnt);
	if (result_2 == (struct approve_request *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_3 = request_access_1(&request_access_1_arg, clnt);
	if (result_3 == (struct access_response *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_4 = validate_delegated_action_1(&validate_delegated_action_1_arg, clnt);
	if (result_4 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}

struct auth_response *request_auth(char *host, char *id) {
	CLIENT *clnt;
	struct auth_response  *auth_response;

#ifndef	DEBUG
	clnt = clnt_create (host, OAUTH_PROG, OAUTH_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	auth_response = request_auth_1(&id, clnt);
	if (auth_response == (struct auth_response *) NULL) {
		clnt_perror (clnt, "call failed");
		exit(1);
	}

	fflush(stdout);
	//printf("Response: %s %d\n", auth_response->auth_token, auth_response->status);
	
	return auth_response;
}

struct approve_request *approve_request_token(char *host, struct approve_request approve_request) {
	CLIENT *clnt;
	struct approve_request *approve_response;

#ifndef	DEBUG
	clnt = clnt_create (host, OAUTH_PROG, OAUTH_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	approve_response = approve_request_token_1(&approve_request, clnt);
	if (approve_response == (struct approve_request *) NULL) {
		clnt_perror (clnt, "call failed");
		exit(1);
	}

	return approve_response;
}

struct access_response *request_access(char *host, struct access_request access_request) {
	
	CLIENT *clnt;
	struct access_response *access_response;

#ifndef	DEBUG
	clnt = clnt_create (host, OAUTH_PROG, OAUTH_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	
	access_response = request_access_1(&access_request, clnt);
	if (access_response == (struct access_response *) NULL) {
		clnt_perror (clnt, "call failed");
		exit(1);
	}

	return access_response;

}

int *validate_delegated_action(char *host, struct action_request action_request) {

	CLIENT *clnt;
	int *response;

#ifndef	DEBUG
	clnt = clnt_create (host, OAUTH_PROG, OAUTH_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	

	response = validate_delegated_action_1(&action_request, clnt);
	if (response == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}

	return response;
}

struct refresh_response *refresh_session(char *host, char *refresh_token) {
	CLIENT *clnt;
	struct refresh_response *response;

#ifndef	DEBUG
	clnt = clnt_create (host, OAUTH_PROG, OAUTH_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	

	response = refresh_session_1(&refresh_token, clnt);
	if (response == (struct refresh_response *) NULL) {
		clnt_perror (clnt, "call failed");
	}

	return response;
}

int
main (int argc, char *argv[])
{
	char *host;
	fflush(stdout);
	
	//printf("lalal\n\n");

	if (argc < 2) {
		printf ("usage: %s server_host operations_file\n", argv[0]);
		exit (1);
	} else if (argc < 3) {
		printf ("no operations file found\n");
		exit (1);
	}

	client_ids = malloc(MAX_LINES * sizeof(char *));
	client_access_tokens = malloc(MAX_LINES * sizeof(char *));
	client_refresh_tokens = malloc(MAX_LINES * sizeof(char *));
	client_ttls = calloc(MAX_LINES, sizeof(int));
	client_refresh_states = calloc(MAX_LINES, sizeof(int));


	for (int i = 0; i < MAX_LINES; i++) {
		client_ids[i] = calloc(16, sizeof(char));
		client_access_tokens[i] = calloc(16, sizeof(char));
		client_refresh_tokens[i] = calloc(16, sizeof(char));
	}

	host = argv[1];
	char *operations_file = argv[2];

	fflush(stdout);
	//printf("%s\n", operations_file);

    FILE *file = fopen(operations_file, "r");  // Open the file in read mode
    if (file == NULL) {
        perror("Error opening file");
        return 1;
    }

    char line[100];  // Buffer to store each line
	const char delimiters[] = ",\n";

	// Execute every command
	int nr = 0;
    while (fgets(line, sizeof(line), file)) {  // Read one line at a time
		//printf("%s %d\n", line, nr);
		nr++;

		char *token = strtok(line, delimiters);
		char id[16];
		strcpy(id, token);

		char action[30];
		token = strtok(NULL, delimiters);
		strcpy(action, token);

		if (strcmp(action, "REQUEST") == 0) {

			char refresh_string[10];
			token = strtok(NULL, delimiters);
			int refresh_state = atoi(token);

			// Search client if the database and save his database id
			int database_id = 0;
			int found = 0;
			for (int i = 0; i < client_nr_users; i++) {
				if (strcmp(client_ids[i], id) == 0) {
					found = 1;
					database_id = i;
					break;
				}
			}

			// Add client to database (if it's his first request).
			if(!found) {
				strcpy(client_ids[client_nr_users], id);
				database_id = client_nr_users;
				client_nr_users++;
			}

			// Send authorization request to server.
			struct auth_response *auth_response = request_auth(host, id);

			if (auth_response->status == 404) {
				printf("USER_NOT_FOUND\n");
			} else {

				// Prepare signature request to user.
				struct approve_request approve_request;
				approve_request.auth_token = malloc(16);
				approve_request.signature = malloc(16);
				approve_request.permissions = malloc(100);
				strcpy(approve_request.auth_token, auth_response->auth_token);

				// Request signature from user.
				struct approve_request *approve_response = approve_request_token(host, approve_request);

				// Stop if signature was not provided.
				if (approve_response->signature[0] == '\0') {
					printf("REQUEST_DENIED\n");
					continue;
				}

				// Prepare access request to server.
				struct access_request access_request;
				access_request.auth_token = malloc(16);
				access_request.id = malloc(16);
				access_request.signature = malloc(16);
				strcpy(access_request.id, id);
				strcpy(access_request.auth_token, approve_response->auth_token);
				strcpy(access_request.signature, approve_response->signature);
				access_request.refresh_state = refresh_state;

				// Request access token
				struct access_response *access_response = request_access(host, access_request);
				
				// Save access token. Set its ttl.
				strcpy(client_access_tokens[database_id], access_response->access_token);
				client_ttls[database_id] = access_response->ttl;
				//printf("%d\n", client_ttls[database_id]);

				// Save refresh state.
				client_refresh_states[database_id] = refresh_state;

				// Save refresh token.
				if (refresh_state) {
					strcpy(client_refresh_tokens[database_id], access_response->refresh_token);
					printf("%s -> %s,%s\n", access_request.auth_token, access_response->access_token, access_response->refresh_token);
				} else {
					memset(client_refresh_tokens[database_id], 0, 16);
					printf("%s -> %s\n", access_request.auth_token, access_response->access_token);
				}

			}
		} else {
			
			// Parse resource's name
			char resource[30];
			token = strtok(NULL, delimiters);
			strcpy(resource, token);

			// Find user.
			int database_id;
			for (database_id = 0; database_id < client_nr_users; database_id++) {
				if (strcmp(client_ids[database_id], id) == 0) {
					break;
				}
			}

			// Check if refresh is needed.
			if (!client_ttls[database_id] && client_refresh_states[database_id]) {

				//printf("REFRESH, NU I BINE DELOC\n");
				// Send refresh request.
				struct refresh_response *refresh_response = refresh_session(host, client_refresh_tokens[database_id]);
				
				// Save new tokens.
				strcpy(client_access_tokens[database_id], refresh_response->access_token);
				strcpy(client_refresh_tokens[database_id], refresh_response->refresh_token);
				client_ttls[database_id] = refresh_response->ttl;
			}
			
			client_ttls[database_id]--;

			struct action_request action_request;
			action_request.action = malloc(2);
			action_request.access_token = malloc(16);
			action_request.resource = malloc(30);

			if (action[0] == 'E') {
				action_request.action[0] = 'X';
			} else {
				action_request.action[0] = action[0];
			}
			action_request.action[1] = '\0'; 

			strcpy(action_request.resource, resource);

			// Append user's access token
			strcpy(action_request.access_token, client_access_tokens[database_id]);

			
			int *status = validate_delegated_action(host, action_request);
			// printf("Status: %d\n", *status);
			switch (*status)
			{
			case PERMISSION_GRANTED:
				printf("PERMISSION_GRANTED\n");
				break;
			case PERMISSION_DENIED:
				printf("PERMISSION_DENIED\n");
				break;
			case TOKEN_EXPIRED:
				printf("TOKEN_EXPIRED\n");
				break;
			case RESOURCE_NOT_FOUND:
				printf("RESOURCE_NOT_FOUND\n");
				break;
			case OPERATION_NOT_PERMITTED:
				printf("OPERATION_NOT_PERMITTED\n");
				break;
			default:
				printf("ERROR!\n");
				break;
			}
		}
		//("\n");
    }

    fclose(file);  // Close the file

	exit (0);
}
