/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _OAUTH_H_RPCGEN
#define _OAUTH_H_RPCGEN

#include <rpc/rpc.h>

#ifdef __cplusplus
extern "C" {
#endif


struct auth_response {
	char *auth_token;
	int status;
};
typedef struct auth_response auth_response;

struct approve_request {
	char *auth_token;
	char *signature;
	char *permissions;
};
typedef struct approve_request approve_request;

struct access_request {
	char *id;
	char *signature;
	char *auth_token;
};
typedef struct access_request access_request;

struct access_response {
	char *access_token;
	char *refresh_token;
	int ttl;
};
typedef struct access_response access_response;

struct action_request {
	char *action;
	char *access_token;
	char *resource;
};
typedef struct action_request action_request;

#define CHECKPROG 0x30000005
#define CHECKVERS 1

// Shared data
#define MAX_LINES 10
extern char **ids;
extern char **resources;
extern char **approvals;
extern char **auth_tokens;

// extern char resources[MAX_LINES][30];
// extern char ids[MAX_LINES][16];
// extern char approvals[MAX_LINES][100];
// extern char auth_tokens[MAX_LINES][16];
extern char **access_tokens;
extern char **refresh_tokens;
extern char **signatures;
extern int nr_users;
extern int nr_resources;
extern int nr_approvals;
extern int crt_approval;
extern int ttl;



#if defined(__STDC__) || defined(__cplusplus)
#define REQUEST_AUTH 1
extern  struct auth_response * request_auth_1(char **, CLIENT *);
extern  struct auth_response * request_auth_1_svc(char **, struct svc_req *);
#define APPROVE_REQUEST_TOKEN 2
extern  struct approve_request * approve_request_token_1(struct approve_request *, CLIENT *);
extern  struct approve_request * approve_request_token_1_svc(struct approve_request *, struct svc_req *);
#define REQUEST_ACCESS 3
extern  struct access_response * request_access_1(struct access_request *, CLIENT *);
extern  struct access_response * request_access_1_svc(struct access_request *, struct svc_req *);
#define VALIDATE_DELEGATED_ACTION 4
extern  int * validate_delegated_action_1(struct access_request *, CLIENT *);
extern  int * validate_delegated_action_1_svc(struct access_request *, struct svc_req *);
extern int checkprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define REQUEST_AUTH 1
extern  struct auth_response * request_auth_1();
extern  struct auth_response * request_auth_1_svc();
#define APPROVE_REQUEST_TOKEN 2
extern  struct approve_request * approve_request_token_1();
extern  struct approve_request * approve_request_token_1_svc();
#define REQUEST_ACCESS 3
extern  struct access_response * request_access_1();
extern  struct access_response * request_access_1_svc();
#define VALIDATE_DELEGATED_ACTION 4
extern  int * validate_delegated_action_1();
extern  int * validate_delegated_action_1_svc();
extern int checkprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_auth_response (XDR *, auth_response*);
extern  bool_t xdr_approve_request (XDR *, approve_request*);
extern  bool_t xdr_access_request (XDR *, access_request*);
extern  bool_t xdr_access_response (XDR *, access_response*);
extern  bool_t xdr_action_request (XDR *, action_request*);

#else /* K&R C */
extern bool_t xdr_auth_response ();
extern bool_t xdr_approve_request ();
extern bool_t xdr_access_request ();
extern bool_t xdr_access_response ();
extern bool_t xdr_action_request ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_OAUTH_H_RPCGEN */
