/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "oauth.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

int ttl;
int nr_users;
int nr_resources;
int nr_approvals;

void create_database(char **argv) {
	char *users_file = argv[1];
	char *resources_file = argv[2];
	char *approvals_file = argv[3];
	ttl = atoi(argv[4]);

	FILE *file = fopen(users_file, "r");
    if (file == NULL) {
        perror("Error opening file");
        return 1;
    }

    char line[100];  // Buffer to store each line
	const char delimiters[] = ",\n";

	// Read every line
	fgets(line, sizeof(line), file);
	nr_users = atoi(line)
    for (int i = 0; i < nr_users; i++) {
		fgets(line, sizeof(line), file);
		strcpy(ids[i], line);
	}
	fclose(file);

	FILE *file = fopen(resources_file, "r");
    if (file == NULL) {
        perror("Error opening file");
        return 1;
    }

	// Read every line
	fgets(line, sizeof(line), file);
	nr_resources = atoi(line)
    for (int i = 0; i < nr_resources; i++) {
		fgets(line, sizeof(line), file);
		strcpy(resources[i], line);
	}
	fclose(file);

	FILE *file = fopen(approvals_file, "r");
    if (file == NULL) {
        perror("Error opening file");
        return 1;
    }

	// Read every line
	fgets(line, sizeof(line), file);
	nr_approvals = atoi(line)
    for (int i = 0; i < nr_approvals; i++) {
		fgets(line, sizeof(line), file);
		strcpy(approvals[i], line);
	}
	fclose(file);

}

static void
checkprog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		char *request_auth_1_arg;
		struct approve_request approve_request_token_1_arg;
		struct access_request request_access_1_arg;
		struct access_request validate_delegated_action_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case REQUEST_AUTH:
		_xdr_argument = (xdrproc_t) xdr_wrapstring;
		_xdr_result = (xdrproc_t) xdr_auth_response;
		local = (char *(*)(char *, struct svc_req *)) request_auth_1_svc;
		break;

	case APPROVE_REQUEST_TOKEN:
		_xdr_argument = (xdrproc_t) xdr_approve_request;
		_xdr_result = (xdrproc_t) xdr_approve_request;
		local = (char *(*)(char *, struct svc_req *)) approve_request_token_1_svc;
		break;

	case REQUEST_ACCESS:
		_xdr_argument = (xdrproc_t) xdr_access_request;
		_xdr_result = (xdrproc_t) xdr_access_response;
		local = (char *(*)(char *, struct svc_req *)) request_access_1_svc;
		break;

	case VALIDATE_DELEGATED_ACTION:
		_xdr_argument = (xdrproc_t) xdr_access_request;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) validate_delegated_action_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (CHECKPROG, CHECKVERS);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, CHECKPROG, CHECKVERS, checkprog_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (CHECKPROG, CHECKVERS, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, CHECKPROG, CHECKVERS, checkprog_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (CHECKPROG, CHECKVERS, tcp).");
		exit(1);
	}


	fflush(stdout);
	if (argc < 4) {
		printf ("usage: %s users_file resources_file approvals_file time_to_live\n", argv[0]);
		exit (1);
	}
	create_database();

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
