/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "oauth.h"

struct auth_response *
request_auth_1_svc(char **argp, struct svc_req *rqstp)
{
	static struct auth_response  result;
	char *id_to_authorize;
	int found = 0;

	/*
	 * insert server code here
	 */

	for(int i = 0; i < nr_users; i++) {
		if (strcmp(ids[i], id_to_authorize) == 0) {
			result.status = 200;
			char *auth_token = generate_access_token(id_to_authorize);
			strcpy(result.request_token, auth_token); // Give client the auth_token
			strcpy(auth_tokens[i], auth_token); // Save the auth token for future verification
			found = 1;
			break;
		}
	}

	if (!found) {
		result.status = 404;
	}

	return &result;
}

struct approve_request *
approve_request_token_1_svc(struct approve_request *approve_request, struct svc_req *rqstp)
{
	static struct approve_request approve_response;

	/*
	 * insert server code here
	 */
	strcpy(approve_response.auth_token, approve_request->auth_token);
	char *user_action = approvals[crt_approval];
	if (user_action[0] == '*') {
		// TODO
		approve_response.signature = NULL;
		approve_response.permissions = NULL;
	} else {
		char *signature = generate_signature_token(approve_request->auth_token);
		strcpy(approve_response.signature, signature);
		strcpy(approve_response.permissions, user_action);
		// Save the signature for future verification
		for (int i = 0; i < nr_users; i++) {
			if (strcmp(approve_request->auth_token, auth_tokens[i]) == 0) {
				strcpy(signatures[i], signature);
				break;
			}
		}
	}

	return &approve_response;
}

struct access_response *
request_access_1_svc(struct access_request *access_request, struct svc_req *rqstp)
{
	static struct access_response  access_response;

	/*
	 * insert server code here
	 */
	for (int i = 0; i < nr_users; i++) {
		if (strmcp(ids[i], access_request->id) == 0) { // User found	 
			if (strcmp(signatures[i], access_request->signature) != 0) {
				return NULL;
			} else {
				char *access_token = generate_access_token(access_request->auth_token);
				char *refresh_token = generate_access_token(access_token);
				strcpy(access_response.access_token, access_token);
				strcpy(access_response.refresh_token, refresh_token);
				access_token.ttl = ttl;
				break
			}
		}
	}

	return &access_response;
}

int *
validate_delegated_action_1_svc(struct access_request *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}
