/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "oauth.h"


void
checkprog_1(char *host)
{
	CLIENT *clnt;
	struct auth_response  *result_1;
	char * request_auth_1_arg;
	struct approve_request  *result_2;
	struct approve_request  approve_request_token_1_arg;
	struct access_response  *result_3;
	struct access_request  request_access_1_arg;
	int  *result_4;
	struct access_request  validate_delegated_action_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, CHECKPROG, CHECKVERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = request_auth_1(&request_auth_1_arg, clnt);
	if (result_1 == (struct auth_response *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = approve_request_token_1(&approve_request_token_1_arg, clnt);
	if (result_2 == (struct approve_request *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_3 = request_access_1(&request_access_1_arg, clnt);
	if (result_3 == (struct access_response *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_4 = validate_delegated_action_1(&validate_delegated_action_1_arg, clnt);
	if (result_4 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}

struct auth_response *request_auth(char *host, char *id) {
	CLIENT *clnt;
	struct auth_response  *auth_response;

#ifndef	DEBUG
	clnt = clnt_create (host, CHECKPROG, CHECKVERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	auth_response = request_auth_1(&id, clnt);
	if (auth_response == (struct auth_response *) NULL) {
		clnt_perror (clnt, "call failed");
		exit(1);
	}

	fflush(stdout);
	printf("Response: %s %d\n", auth_response->auth_token, auth_response->status);
	
	return auth_response;
}

struct approve_request *approve_request_token(char *host, struct approve_request approve_request) {
	CLIENT *clnt;
	struct approve_request *approve_response;

#ifndef	DEBUG
	clnt = clnt_create (host, CHECKPROG, CHECKVERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	approve_response = approve_request_token_1(&approve_request, clnt);
	if (approve_response == (struct approve_request *) NULL) {
		clnt_perror (clnt, "call failed");
		exit(1);
	}

	return approve_response;
}

struct access_response *request_access(char *host, struct access_request access_request) {
	
	CLIENT *clnt;
	struct access_response *access_response;

#ifndef	DEBUG
	clnt = clnt_create (host, CHECKPROG, CHECKVERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	
	access_response = request_access_1(&access_request, clnt);
	if (access_response == (struct access_response *) NULL) {
		clnt_perror (clnt, "call failed");
		exit(1);
	}

	return access_response;

}

int
main (int argc, char *argv[])
{
	char *host;
	fflush(stdout);
	printf("lalal\n\n");

	if (argc < 2) {
		printf ("usage: %s server_host operations_file\n", argv[0]);
		exit (1);
	} else if (argc < 3) {
		printf ("no operations file found\n");
		exit (1);
	}

	host = argv[1];
	char *operations_file = argv[2];

	fflush(stdout);
	printf("%s\n", operations_file);

    FILE *file = fopen(operations_file, "r");  // Open the file in read mode
    if (file == NULL) {
        perror("Error opening file");
        return 1;
    }

    char line[100];  // Buffer to store each line
	const char delimiters[] = ",\n";

	// Execute every command
	int nr = 0;
    while (fgets(line, sizeof(line), file)) {  // Read one line at a time
	printf("%s\n", line);
		printf("%d\n", nr);
		nr++;
		printf("\n\n");
		char *token = strtok(line, delimiters);
		char id[16];
		strcpy(id, token);
		char action[30];
		token = strtok(NULL, delimiters);
		strcpy(action, token);
		char refresh_string[10];
		token = strtok(NULL, delimiters);
		int refresh = atoi(token);

		if (strcmp(action, "REQUEST") == 0) {
			// Send authorization request to server
			struct auth_response *auth_response = request_auth(host, id);
			if (auth_response->status == 404) {
				printf("USER_NOT_FOUND\n");
			} else {

				// Prepare signature request to user
				struct approve_request approve_request;
				approve_request.auth_token = malloc(16);
				approve_request.signature = malloc(16);
				approve_request.permissions = malloc(100);
				strcpy(approve_request.auth_token, auth_response->auth_token);

				// Request signature from user
				struct approve_request *approve_response = approve_request_token(host, approve_request);
				printf("app %s\n", approve_response->signature);

				// Prepare access request to server
				if (approve_response->signature[0] == '\0') {
					printf("REQUEST_DENIED\n");
					continue;
				}
				struct access_request access_request;
				access_request.auth_token = malloc(16);
				access_request.id = malloc(16);
				access_request.signature = malloc(16);
				strcpy(access_request.id, id);
				strcpy(access_request.auth_token, approve_response->auth_token);
				strcpy(access_request.signature, approve_response->signature);

				// Request access token
				printf("before access\n");
				struct access_response *access_response = request_access(host, access_request);
				printf("after access\n");
				if (!access_response) {
					printf("REQUEST_DENIED\n");
				} else {
					printf("%s -> %s\n", access_request.auth_token, access_response->access_token);
				}
			}
		}
    }

    fclose(file);  // Close the file

	exit (0);
}
